[package]
name = "ravif"
description = "rav1e-based pure Rust library for encoding images in AVIF format (powers the `cavif` tool)"
version = "0.8.7"
authors = ["Kornel Lesiński <kornel@geekhood.net>"]
edition = "2018"
license = "BSD-3-Clause"
readme = "README.md"
keywords = ["avif", "convert", "av1", "rav1f", "cav1f"]
categories = ["multimedia::images", "multimedia::encoding"]
homepage = "https://lib.rs/ravif"
repository = "https://github.com/kornelski/cavif-rs"
include = ["README.md", "LICENSE", "Cargo.toml", "/src/*.rs"]
resolver = "2"

[dependencies]
avif-serialize = { git = "https://github.com/kornelski/avif-serialize", rev="f6114cc73623223146836b6baed9c1db02d04926" }
num_cpus = "1.13.0"
rav1e = { git = "https://github.com/xiph/rav1e", rev="8d1d0a6c4263024dc13bc88b00c5d5fe9be3cf12", default-features = false }
rayon = "1.5.1"
rgb = "0.8.27"
imgref = "1.9.0"
loop9 = "0.1.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
rav1e = { git = "https://github.com/xiph/rav1e", rev="8d1d0a6c4263024dc13bc88b00c5d5fe9be3cf12", features = ["wasm"] }

[features]
default = ["asm"]
asm = ["rav1e/asm"]

[profile.release]
lto = true

[profile.dev.package."*"]
debug = false
opt-level = 2

[dev-dependencies]
avif-parse = "0.13.2"
